version: '2'

services:
  webserver:
    build: ./webserver
    image: runwaytest_web
    ports:
      - "8081:80"
      - "4430:443"
    volumes:
      - /home/morgan/Bureau/docker:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
    links:
      - db
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - db:db
      ports:
          - "8080:80"
      environment:
          - MYSQL_USERNAME=root
          - MYSQL_PASSWORD=root
  db:
    image: mysql:5.7
    ports:
      - "8082:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=forum
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
